//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BazanovSava1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Колво сахара.
    /// </summary>
    // *** Start programmer edit section *** (КолвоСахара CustomAttributes)

    // *** End programmer edit section *** (КолвоСахара CustomAttributes)
    public enum КолвоСахара
    {
        
        // *** Start programmer edit section *** (КолвоСахара.БезСахара CustomAttributes)

        // *** End programmer edit section *** (КолвоСахара.БезСахара CustomAttributes)
        [Caption("БезСахара")]
        БезСахара,
        
        // *** Start programmer edit section *** (КолвоСахара.ОдинКубик CustomAttributes)

        // *** End programmer edit section *** (КолвоСахара.ОдинКубик CustomAttributes)
        [Caption("ОдинКубик")]
        ОдинКубик,
        
        // *** Start programmer edit section *** (КолвоСахара.ДваКубика CustomAttributes)

        // *** End programmer edit section *** (КолвоСахара.ДваКубика CustomAttributes)
        [Caption("ДваКубика")]
        ДваКубика,
        
        // *** Start programmer edit section *** (КолвоСахара.ТриКубика CustomAttributes)

        // *** End programmer edit section *** (КолвоСахара.ТриКубика CustomAttributes)
        [Caption("ТриКубика")]
        ТриКубика,
        
        // *** Start programmer edit section *** (КолвоСахара.ЧетыреКубика CustomAttributes)

        // *** End programmer edit section *** (КолвоСахара.ЧетыреКубика CustomAttributes)
        [Caption("ЧетыреКубика")]
        ЧетыреКубика,
        
        // *** Start programmer edit section *** (КолвоСахара.ПятьКубиков CustomAttributes)

        // *** End programmer edit section *** (КолвоСахара.ПятьКубиков CustomAttributes)
        [Caption("ПятьКубиков")]
        ПятьКубиков,
    }
}
