//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BazanovSava1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Напитки.
    /// </summary>
    // *** Start programmer edit section *** (Напитки CustomAttributes)

    // *** End programmer edit section *** (Напитки CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НапиткиE", new string[] {
            "Наименование as \'Наименование\'",
            "Состав as \'Состав\'",
            "Цена as \'Цена\'"})]
    [View("НапиткиL", new string[] {
            "Наименование as \'Наименование\'",
            "Состав as \'Состав\'",
            "Цена as \'Цена\'"})]
    public class Напитки : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fСостав;
        
        private double fЦена;
        
        // *** Start programmer edit section *** (Напитки CustomMembers)

        // *** End programmer edit section *** (Напитки CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Напитки.Наименование CustomAttributes)

        // *** End programmer edit section *** (Напитки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Напитки.Наименование Get start)

                // *** End programmer edit section *** (Напитки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Напитки.Наименование Get end)

                // *** End programmer edit section *** (Напитки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Напитки.Наименование Set start)

                // *** End programmer edit section *** (Напитки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Напитки.Наименование Set end)

                // *** End programmer edit section *** (Напитки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Состав.
        /// </summary>
        // *** Start programmer edit section *** (Напитки.Состав CustomAttributes)

        // *** End programmer edit section *** (Напитки.Состав CustomAttributes)
        [StrLen(255)]
        public virtual string Состав
        {
            get
            {
                // *** Start programmer edit section *** (Напитки.Состав Get start)

                // *** End programmer edit section *** (Напитки.Состав Get start)
                string result = this.fСостав;
                // *** Start programmer edit section *** (Напитки.Состав Get end)

                // *** End programmer edit section *** (Напитки.Состав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Напитки.Состав Set start)

                // *** End programmer edit section *** (Напитки.Состав Set start)
                this.fСостав = value;
                // *** Start programmer edit section *** (Напитки.Состав Set end)

                // *** End programmer edit section *** (Напитки.Состав Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Напитки.Цена CustomAttributes)

        // *** End programmer edit section *** (Напитки.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Напитки.Цена Get start)

                // *** End programmer edit section *** (Напитки.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Напитки.Цена Get end)

                // *** End programmer edit section *** (Напитки.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Напитки.Цена Set start)

                // *** End programmer edit section *** (Напитки.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Напитки.Цена Set end)

                // *** End programmer edit section *** (Напитки.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НапиткиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НапиткиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НапиткиE", typeof(IIS.BazanovSava1.Напитки));
                }
            }
            
            /// <summary>
            /// "НапиткиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НапиткиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НапиткиL", typeof(IIS.BazanovSava1.Напитки));
                }
            }
        }
    }
}
